function d=StratProfile(u,t)
%% Description
% Turns outputs (age depth distributions) generated by the PartiMoDe model
% and its special cases (LoFi and StEn) into stratigraphic profiles
% Author: Niklas Hohmann
% email: N.H.Hohmann (at) uu.nl , ORCID: https://orcid.org/0000-0003-1559-1838
%% Inputs:
% u: Matrix output generated by functions PartiMoDe, PartiMode_LoFi, or PartiMode_StEn
% t: Vector with strictly increasing positive numbers.
%       corresponds to input "times" in PartiMoDe and PartiMoDe_StEn
%       corresponds to input "ages" from PartiThe_LoFi
%% Outputs
% d: Vector. d(i) is the density of particles at depth depths(i), where
%       depths is the input "depths" in PartiMoDe, PartiMoDe_StEn,
%       and PartiThe_LoFi
%% See also
% * File "Example_PartiMoDe.m" for an example
% * Function PartiMoDe_LoFi: particle input changes with time
% * Function PartiMoDe_StEn: effects are depth dependent
% * Function PartiMoDe: effects are time and depth dependent
%% Function Body
d=zeros(size(u,1),1); % initialize storage
for i= 1:size(u,1)
    % determine integral over time/age using the trapezoidal rule
    d(i)=sum(0.5*diff(t).*(u(i,1:(length(t)-1))+u(i,2:length(t)))); 
end

